 steps:
 # pull down the latest version of the image to speed up building
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker pull gcr.io/$PROJECT_ID/caendr-site-v2:latest || exit 0']
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA', '-f', './src/modules/site-v2/Dockerfile.cloudrun', '--cache-from', 'gcr.io/$PROJECT_ID/caendr-site-v2:latest',  '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'caendr-site-v2'
   - '--image'
   - 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA'
   - '--region'
   - 'REGION'
 images:
 - 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA'