 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA', '-f', './src/modules/site-v2/Dockerfile.cloudrun','.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'caendr-site-v2'
   - '--image'
   - 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA'
   - '--region'
   - 'REGION'
 images:
 - 'gcr.io/$PROJECT_ID/caendr-site-v2:$COMMIT_SHA'