from setuptools import setup

setup(
  name='caendr',
  version='1.0.1',
  packages=['caendr'],
  install_requires=[
    'backoff==2.2.1',
    'cachelib',
    'cyvcf2==0.30.22',
    'Flask_SQLAlchemy==2.5.1',
    'Flask==1.1.2',
    'protobuf==3.20.2',
    'google-cloud-appengine-logging==0.1.0',
    'google_cloud_audit_log==0.2.5',
    'google-api-python-client',
    'google-cloud-datastore',
    'google_cloud_logging',
    'google-cloud-run',
    'google-cloud-secret-manager',
    'google-cloud-storage',
    'google-cloud-tasks',
    'gspread==3.6.0',
    'gtfparse==0.0.6',
    'logzero==1.3.1',
    'oauth2client',
    'numpy==1.19.5',
    'pandas==1.1.3',
    'plotly==5.3.0',
    'psycopg2-binary>=2.9.1',
    'pg8000',
    'python-dotenv==0.19.1',
    'pytabix==0.1',
    'importlib; python_version == "3.8.10"',
    'scipy',
    'Werkzeug==1.0.0'
  ],
)
