version: '3.8'

services:
  postgres:
    image: postgres:13.5-alpine
    restart: always
    env_file:
      - src/modules/site-v2/.env
    environment:
      - POSTGRES_USER=$MODULE_DB_OPERATIONS_DB_USER_NAME
      - POSTGRES_DB=$MODULE_DB_OPERATIONS_DB_NAME
      - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    storage_opt:
      size: '10G'

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.28.1-alpine
    restart: always
    env_file:
      - src/modules/site-v2/.env
    volumes:
      - $GOOGLE_APPLICATION_CREDENTIALS:/config
    ports:
      - "5432:5432"
    command: "/cloud_sql_proxy -instances=$GOOGLE_CLOUD_PROJECT_ID:$GOOGLE_CLOUD_REGION:$MODULE_DB_OPERATIONS_INSTANCE_NAME=tcp:0.0.0.0:5432 -credential_file=/config"
