import os

from dotenv import load_dotenv

from caendr.services.cloud.secret import get_secret

dotenv_file = '.env'
load_dotenv(dotenv_file)

download_path = ".download"

GOOGLE_CLOUD_PROJECT_ID = os.environ.get('GOOGLE_CLOUD_PROJECT_ID')
GOOGLE_CLOUD_REGION = os.environ.get('GOOGLE_CLOUD_REGION')
MODULE_SITE_POSTGRES_INSTANCE_NAME = os.environ.get('MODULE_SITE_POSTGRES_INSTANCE_NAME')
MODULE_SITE_POSTGRES_DB_NAME = os.environ.get('MODULE_SITE_POSTGRES_DB_NAME')
MODULE_SITE_POSTGRES_DB_STAGE_NAME = os.environ.get('MODULE_SITE_POSTGRES_DB_STAGE_NAME')
MODULE_DB_OPS_POSTGRES_DB_USER = os.environ.get('MODULE_DB_OPS_POSTGRES_DB_USER')
POSTGRES_DB_PASSWORD = get_secret('POSTGRES_DB_PASSWORD')

DB_INSTANCE_URI = f'{GOOGLE_CLOUD_PROJECT_ID}:{GOOGLE_CLOUD_REGION}:{MODULE_SITE_POSTGRES_INSTANCE_NAME}'
DB_CONN_URI = f'postgres+psycopg2://{MODULE_DB_OPS_POSTGRES_DB_USER}:{POSTGRES_DB_PASSWORD}@/{MODULE_SITE_POSTGRES_INSTANCE_NAME}?host=/cloudsql/{DB_INSTANCE_URI}'

